font_family        Fira Code Retina
bold_font          Fira Code SemiBold

font_size 14.0

modify_font cell_height +2px

modify_font underline_position 4
modify_font underline_thickness 300%

# disable_ligatures never
disable_ligatures cursor

font_features FiraCode-Light +cv02 +ss01 +ss03 +ss05 +ss09 +zero
font_features FiraCodeRoman-Regular +cv02 +ss01 +ss03 +ss05 +ss09 +zero
font_features FiraCodeRoman-Medium +cv02 +ss01 +ss03 +ss05 +ss09 +zero
font_features FiraCodeRoman-Bold +cv02 +ss01 +ss03 +ss05 +ss09 +zero
font_features FiraCodeRoman-SemiBold +cv02 +ss01 +ss03 +ss05 +ss09 +zero
font_features FiraCode-Retina +cv02 +ss01 +ss03 +ss05 +ss09 +zero

cursor_shape beam

cursor_blink_interval 0

enable_audio_bell no

tab_bar_edge top

tab_bar_style fade

macos_option_as_alt both

editor  /opt/homebrew/bin/nvim

shell_integration enabled

include ./nord.conf
