local M = {
	"stevearc/aerial.nvim",
	cmd = { "AerialToggle" },
}

M.opts = {
	backends = { "markdown", "lsp", "treesitter", "man" },
	layout = {
		max_width = 0.2,
		min_width = 0.15,
		default_direction = "right",
		-- placement = "window",
		placement = "edge",
		preserve_equality = true,
	},
	attach_mode = "global",
	disable_max_lines = nil,
	disable_max_size = nil, -- Default 2MB
	filter_kind = {
		"Array",
		"Boolean",
		"Class",
		"Constructor",
		"Constant",
		"Enum",
		"EnumMember",
		"Event",
		"Field",
		"File",
		"Function",
		"Interface",
		"Key",
		"Module",
		"Method",
		"Namespace",
		"Number",
		"Object",
		"Package",
		"Property",
		"String",
		"Struct",
		"TypeParameter",
		"Variable",
	},
	highlight_on_hover = true,
	icons = {
		File = "󰈙",
		Module = "",
		Namespace = "󰅪",
		Package = "󰏖",
		Class = "󰠱",
		Method = "󰆧",
		Variable = "󰂡",
		Field = "󰇽",
		Unit = "",
		Value = "󰎠",
		Interface = "",
		Function = "󰊕",
		Constant = "",
		Constructor = "",
		String = "𝓐",
		Number = "#",
		Boolean = "⊨",
		Array = "󰅪",
		Object = "⦿",
		Enum = "",
		Property = "󰜢",
		Key = "🔐",
		Null = "NULL",
		EnumMember = "",
		Struct = "",
		Event = "",
		Operator = "󰆕",
		TypeParameter = "󰅲",
		Text = "",
	},
	show_guides = true,
}

return M
