version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = '#B48EAD'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .Path }}'
    foreground = '#81A1C1'
    background = 'transparent'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'plain'
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = '#616E88'
    background = 'transparent'
    type = 'git'

    [blocks.segments.properties]
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    foreground = '#BF616A'
    background = 'transparant'
    type = 'status'

    [blocks.segments.properties]
      status_template = '{{ reason .Code }} {{ .Code }}'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ .FormattedMs }}'
    foreground = '#EBCB8B'
    background = 'transparent'
    type = 'executiontime'

    [blocks.segments.properties]
      threshold = 1000

  [[blocks.segments]]
    style = 'plain'
    foreground = '#A3BE8C'
    type = 'time'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '❯'
    background = 'transparent'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']
